### ISSUE TITLE
ネット接続していない状態で起動したい

### ISSUE THREAD

**Issue by z80-2024** [Zuntan03/EasyReforge#3]
「ネット接続していない状態」で起動する簡単な方法がありましたら教えて下さい（Reforge.bat の編集、など）

ネット接続している状態では Reforge.bat で問題なく起動できます。

しかし、「ネット接続していない状態」では Reforge.bat にて起動しようとしてもエラーが発生して起動できません。
エラーメッセージ：　RuntimeError: Couldn't install requirements.

インストール完了後も Reforge.bat での起動時にはコマンドプロンプトに毎回 "Installing requirements" と表示される為、毎回起動時にネットワークを参照して最新版をインストールしようとするもののネットワーク接続できないためエラーが発生している感じがします。

**Comment by z80-2024** [comment]
自己解決できたかもしれませんので報告します。

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings
を参考にして Reforge.bat を編集（"--skip-install" を追記）したところ「ネット接続していない状態」でも起動できるようになりました。

この状態にて暫く様子を見てみます。

**Comment by Zuntan03** [comment]
ノウハウの共有、ありがとうございます。
Reforge_ArgSample_DarkTheme.bat をコピーして、`--theme dark` の部分を `--skip-install` に書き換えて使うようにすると、`Update.bat` による更新時に問題が発生しなくなるはずです。

**Comment by z80-2024** [comment]
更新時の対応回答ありがとうございました。
Update.bat による更新時に確認致します。
