### ISSUE TITLE
インストールエラー

### ISSUE THREAD

**Issue by yuriwalker** [Zuntan03/EasyReforge#4]
はじめまして、Yuriです。

早速本題に入らせていただきますと、Panchovix氏がsd-webui-lora-block-weight-reforgeのリポジトリを非公開の状態にしているらしくエクステの追加に失敗しバッチインストールできない状態であります。

エラー発生場所:
EasyReforge\Reforge\ReforgeExtension.batの77~79行目

参考:
https://github.com/Panchovix/sd-webui-lora-block-weight-reforge
(Page Not Found)

上記につきまして、修正対応のほどお願いしてもらってもよろしいでしょうか。
以上です。

**Comment by githabtane** [comment]
同様です
拡張機能のインストールが出来ていない状況です

**Comment by Zuntan03** [comment]
不具合の報告、ありがとうございます。
builtin の sd-webui-lora-block-weight-reforge を使うように修正しました。
